### ISSUE TITLE
Mat.at<Vec3b>  i can't find 

### ISSUE THREAD

**Issue by ryj438591419** [EnoxSoftware/OpenCVForUnity#19]

**Comment by EnoxSoftware** [comment]
Since this asset is a clone of OpenCV Java, you are able to use the same API as OpenCV Java.http://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/index.html
If there is implementation example using "OpenCV Java", I think that it can be implemented even using "OpenCV for Unity".

http://answers.opencv.org/question/14978/how-to-editreading-pixels-from-matvec3b-using-java/
