### ISSUE TITLE
estimateRigidTransform not supported in ver 2.3.3

### ISSUE THREAD

**Issue by maja3d** [EnoxSoftware/OpenCVForUnity#33]
I need to use estimateRigidTransform but it's not in ver 2.3.3
I noticed it's in ver 2.3.2 https://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/class_open_c_v_for_unity_1_1_video.html
How can I use this method?
Is there a new equivalent?

Please respond.
Thank you.

**Comment by EnoxSoftware** [comment]
Thank you for your inquiry.

The EstimateRigidTransform () method is deprecated.
It seems to be recommended to use the estimateAffine2D () method instead of the estimateRigidTransform () method.

https://github.com/opencv/opencv/blob/a4ab60920f4c09a20b18052ec7e54561d2eb42e5/modules/video/include/opencv2/video/tracking.hpp#L252-L253
@deprecated Use cv::estimateAffine2D, cv::estimateAffinePartial2D instead. If you are using this fuction
with images, extract points using cv::calcOpticalFlowPyrLK and then use the estimation fuctions.


Regerds,
EnoxSoftware
