### ISSUE TITLE
WebTextureToMat on iOS iPad Air2 (maybe ARM64?)

### ISSUE THREAD

**Issue by samw3** [EnoxSoftware/OpenCVForUnity#4]
I'm running the WebTextureToMat Sample just fine on my iPad mini and iPad 3 and 4, but when I try it on my new iPad Air2, it doesn't work.  It just flashes the screen briefly and goes blue.   This happens with all the WebCam samples except ComicFilter which just shows a black screen.

**Comment by samw3** [comment]
I'm using Unity 5.0.1f1 Personal

**Comment by EnoxSoftware** [comment]
Please choose OpenGL ES2.0 or 3.0 in [PlayerSettings]-[Other Settings]-[Configuration]-[Graphics API].
or
Please test in Unity 5.1.0b4.

**Comment by samw3** [comment]
Using ES2.0 works.  Is this a Unity bug?

**Comment by EnoxSoftware** [comment]
Yes.
An error occurred when using the WebCamTexture.GetPixels32 () in Unity4.6.3 or 5.0.0 or 5.0.1.
http://issuetracker.unity3d.com/issues/calling-unloadunusedassets-after-getpixels-causes-crash

So, without the use of GetPixels32() in Unity4.6.3 or 5.0.0 or 5.0.1, it is used instead LowLevelTextureToMat (). However, LowLevelTextureToMat () is because the "Metal" does not support, you must use the "OpenGLES".

This error has been fixed in Unity4.6.4 and 5.1.0.
