### ISSUE TITLE
How to extract human full body from video

### ISSUE THREAD

**Issue by peterchen2001** [EnoxSoftware/OpenCVForUnity#48]
Hi,

With Opencvforunity, how to extract human full body from video via web camera? Thanks in advance if you can give any clues or code snippet for me.

**Comment by EnoxSoftware** [comment]
OpenPoseExample is included in OpenCVForUnity.
https://github.com/EnoxSoftware/Ope...inModules/dnn/CaffeExample/OpenPoseExample.cs
for now, Since OpenCV's Dnn module uses a CPU, OpenPoseExample takes more than 900 ms to estimate human pose. Perhaps real-time processing is difficult.
But, this repository using OpenCVForUnity seems to work in real-time.
https://twitter.com/yukihiko_a/status/1131174274708910080
https://github.com/yukihiko/ThreeDPoseUnityForiOS

**Comment by peterchen2001** [comment]
Thanks for your quick reply. The posts you provided are very helpful for you. However, what exactly I want is to remove background from each frame of capturing web camera, something like what https://www.remove.bg/ does for persons. Any ideas to make this feature via opencvforunity? thanks in advance.

**Comment by EnoxSoftware** [comment]
BackgroundSubtractorMOG2Example
https://github.com/EnoxSoftware/OpenCVForUnity/blob/master/Assets/OpenCVForUnity/Examples/MainModules/video/BackgroundSubtractorMOG2Example/BackgroundSubtractorMOG2Example.cs

MaskRCNNExample
https://github.com/EnoxSoftware/OpenCVForUnity/blob/master/Assets/OpenCVForUnity/Examples/MainModules/dnn/TensorFlowExample/MaskRCNNExample.cs

**Comment by peterchen2001** [comment]
Yes,that's what I want. Thanks very much!
