### ISSUE TITLE
InputArray class

### ISSUE THREAD

**Issue by A00107408** [EnoxSoftware/OpenCVForUnity#85]
Does OpenCVForUnity have an InputArray class? If not, what is the equivalent?

**Comment by EnoxSoftware** [comment]
Since this asset is a clone of OpenCV Java, you are able to use the same API as OpenCV Java.
https://docs.opencv.org/4.5.0/javadoc/index.html
https://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/annotated.html  
There is no InputArray class in OpenCV Java. In OpenCV Java, the Mat class is used as a container for data input and output.

**Comment by A00107408** [comment]
This is the best news ever. Thank you so much :)
