### ISSUE TITLE
unity android arm64 failed

### ISSUE THREAD

**Issue by gushenjie** [EnoxSoftware/OpenCVForUnity#99]
![微信图片_20210311162908](https://user-images.githubusercontent.com/10531802/110757961-eee2c680-8286-11eb-8b83-9c5d1929492a.png)

**Comment by EnoxSoftware** [comment]
Is ImportSettings of "arm64-v8a / libopencvforunity.so" set correctly?
![image](https://user-images.githubusercontent.com/7920392/110781268-07fc6f00-82a9-11eb-9d67-a26d8f1f007f.png)


![image](https://user-images.githubusercontent.com/7920392/110781291-10ed4080-82a9-11eb-9730-9d839ee692b6.png)

![image](https://user-images.githubusercontent.com/7920392/110781319-1d719900-82a9-11eb-853d-4796ef0e9bf2.png)

**Comment by gushenjie** [comment]
I used your software and found that the ORB algorithm did not recognize the correct angle, and the blue axis jittered very badly. I tried to use the AKAZE algorithm and found that it was very time-consuming. I finally wanted to have image recognition and tracking functions on my phone. Similar to the effect of Vuforia, do you have any optimized solutions and suggestions?

**Comment by EnoxSoftware** [comment]
[MarkerLessARExample](https://github.com/EnoxSoftware/MarkerLessARExample) Code is a rewrite of https://github.com/MasteringOpenCV/code/tree/master/Chapter3_MarkerlessAR using “OpenCV for Unity”. The algorithm is described in detail in "Mastering OpenCV with Practical Computer Vision Projects".
https://github.com/MasteringOpenCV/code/issues/52  
http://www.packtpub.com/cool-projects-with-opencv/book
Since this example is a tutorial code, I recommend using Vuforia etc. for more advanced functions.

**Comment by gushenjie** [comment]
I see that your version 2.3.8 has android x86, which is not in the latest version. Can you add a modified architecture version to the latest version? You can see the picture you sent me above.

**Comment by EnoxSoftware** [comment]
The x86 architecture is no longer supported in Unity 2019.3 and later.  So OpenCVForUnity has also ended x86 support.
https://blogs.unity3d.com/2019/03/05/android-support-update-64-bit-and-app-bundles-backported-to-2017-4-lts/

**Comment by gushenjie** [comment]
thanks
